// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exkqfiglrlkzuabylwph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4a3FmaWdscmxrenVhYnlsd3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTE4NDEsImV4cCI6MjA2MDM4Nzg0MX0.hGGtqa8ZSLphoUlcOC_wOGtrCi13hnL_WhFQOcu-A_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);